# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

services:
  mcp-server:
    build:
      context: mcp
    container_name: docker-server_${PROJECT_NAME}
    restart: always
    ports:
      - 8000:80
    networks:
      - modelcontextprotocol-net
    volumes:
      - ${SOURCE_DIR}/server:/app
    working_dir: /app

  inspector:
    build:
      context: inspector
    container_name: docker-inspector_${PROJECT_NAME}
    restart: always
    ports:
      - 6274:6274
      - 6277:6277
    networks:
      - modelcontextprotocol-net

networks:
  modelcontextprotocol-net:
    driver: bridge
